services:

  carbonio-mailbox:
    hostname: mbox01.carbonio.localhost
    volumes:
      - app-volume_cluster_mbox01:/localconfig
      - mailbox_data_cluster_mbox01:/opt/zextras/data/mailbox
      - mailbox_index_cluster_mbox01:/opt/zextras/index
      - mailbox_store_cluster_mbox01:/opt/zextras/store

  carbonio-mariadb:
    volumes:
      - mariadb_data_cluster_mbox01:/var/lib/mysql

  carbonio-mailbox02:
    image: ${CARBONIO_MAILBOX_IMAGE:-registry.dev.zextras.com/dev/carbonio-mailbox:${CARBONIO_GLOBAL_IMAGES_TAG:-devel}}
    labels:
      - "servicePort=8080"
    hostname: mbox02.carbonio.localhost
    ports:
      - "5006:5005"
    restart: on-failure
    environment:
      - LDAP_URL=ldap://carbonio-openldap:1389
      - LDAP_ROOT_PASSWORD=qh6hWZvc
      - LDAP_ADMIN_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_URL=carbonio-mariadb02
      - MARIADB_PORT=3306
      - CARBONIO_FILES_SERVICE_URL=http://carbonio-files:10000
      - CARBONIO_PREVIEW_SERVICE_URL=http://carbonio-preview:10000
    volumes:
      - app-volume_cluster_mbox02:/localconfig
      - mailbox_data_cluster_mbox02:/opt/zextras/data/mailbox
      - mailbox_index_cluster_mbox02:/opt/zextras/index
      - mailbox_store_cluster_mbox02:/opt/zextras/store
    healthcheck:
      interval: 10s
      retries: 100
      start_period: 40s
      test: curl --fail --silent localhost:8080/service/health/ready || exit 1
      timeout: 20s
    depends_on:
      event-listener:
        condition: service_started
      carbonio-openldap:
        condition: service_healthy
      carbonio-postfix:
        condition: service_healthy
      carbonio-mailbox:
        condition: service_healthy
      carbonio-mariadb02:
        condition: service_started

  carbonio-mariadb02:
    image: ${CARBONIO_MARIADB_IMAGE:-registry.dev.zextras.com/dev/carbonio-mariadb:${CARBONIO_GLOBAL_IMAGES_TAG:-devel}}
    volumes:
      - mariadb_data_cluster_mbox02:/var/lib/mysql

  carbonio-postgres:
    volumes:
      - postgres_data_cluster:/var/lib/postgresql/data
      - ./postgres/init_files.sql:/docker-entrypoint-initdb.d/init_files.sql
      - ./postgres/init_wsc.sql:/docker-entrypoint-initdb.d/init_wsc.sql
      - ./postgres/init_advanced.sql:/docker-entrypoint-initdb.d/init_advanced.sql

  carbonio-storages:
    volumes:
      - storages_data_cluster:/storage

  carbonio-message-broker:
    volumes:
      - carbonio-message-broker_data_cluster:/var/lib/rabbitmq

  consul:
    volumes:
      - consul-data-cluster:/consul/data

  carbonio-videoserver:
    volumes:
      - shared-videoserver-cluster:/var/lib/videoserver

  carbonio-composed-ui:
    hostname: proxy.localhost
volumes:
  mariadb_data_cluster_mbox01:
  mailbox_data_cluster_mbox01:
  mailbox_index_cluster_mbox01:
  mailbox_store_cluster_mbox01:
  app-volume_cluster_mbox01:
  mariadb_data_cluster_mbox02:
  mailbox_data_cluster_mbox02:
  mailbox_index_cluster_mbox02:
  mailbox_store_cluster_mbox02:
  app-volume_cluster_mbox02:
  postgres_data_cluster:
  storages_data_cluster:
  carbonio-message-broker_data_cluster:
  consul-data-cluster:
  shared-videoserver-cluster:

