{{- if .Values.groups.files.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: carbonio-files
  labels:
    app: carbonio-files
spec:
{{- if eq .Values.platform "k3s" }}
  enableServiceLinks: false
  imagePullSecrets:
    - name: {{ .Values.image.pullSecret.name }}
{{- end }}
  containers:
    - name: app
      image: {{ required "images.carbonio-files is required" (index .Values.images "carbonio-files") }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/zextras/opentelemetry-javaagent.jar -Dsun.net.inetaddr.ttl=0"
        - name: _JAVA_OPTIONS
          value: "-Xms128m -Xmx512m"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://carbonio-monitoring:4318"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
{{- if not .Values.monitoring.enabled }}
        - name: OTEL_SDK_DISABLED
          value: "true"
{{- end }}
      command: ["/bin/sh", "-c"]
      args:
        - |
          while [ ! -f /etc/carbonio/files/service-discover/token ]; do sleep 1; done
          export CONSUL_HTTP_TOKEN=$(cat /etc/carbonio/files/service-discover/token)
          exec /app/entrypoint.sh
      volumeMounts:
        - name: files-token
          mountPath: /etc/carbonio/files/service-discover
    - name: consul-agent
      image: {{ required "images.consul is required" (index .Values.images "consul") }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true
    - name: sidecar
      image: {{ required "images.carbonio-files-sidecar is required" (index .Values.images "carbonio-files-sidecar") }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: files-token
          mountPath: /shared-tokens
  volumes:
    - name: files-token
      emptyDir: {}
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
{{- end }}
