{{- if .Values.groups.files.enabled }}
{{- if eq .Values.platform "k3s" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbonio-files
  labels:
    app: carbonio-files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbonio-files
  template:
    metadata:
      labels:
        app: carbonio-files
    spec:
{{ include "carbonio.deployment.k3sPodDefaults" . | indent 6 }}
{{ include "carbonio.files.podbody" . | indent 6 }}
{{- else }}
apiVersion: v1
kind: Pod
metadata:
  name: carbonio-files
  labels:
    app: carbonio-files
spec:
{{ include "carbonio.files.podbody" . | indent 2 }}
{{- end }}
{{- end }}
