services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-config.yaml" ]
    volumes:
      - ./monitoring/otel/otel-config.yaml:/etc/otel-config.yaml
    depends_on:
      - dozzle
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  carbonio-mailbox:
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/zextras/opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=mailbox
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - otel-collector

  carbonio-storages:
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/zextras/opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=storages-service
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - otel-collector

  carbonio-files:
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/zextras/opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=files
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - otel-collector