services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  loki:
    image: grafana/loki:3.5.8
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/lokiconfig.yaml:/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./monitoring/tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    restart: always


  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-config.yaml" ]
    volumes:
      - ./monitoring/otel/otel-config.yaml:/etc/otel-config.yaml
    depends_on:
      - dozzle
      - tempo
      - loki
      - grafana
  grafana:
    image: grafana/grafana:12.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki

  carbonio-mailbox:
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/zextras/opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=mailbox
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - otel-collector