apiVersion: v1
kind: Pod
metadata:
  name: carbonio-docs-editor
  labels:
    app: carbonio-docs-editor
spec:
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-docs-editor:devel
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add: [MKNOD, SYS_ADMIN, FOWNER, CHOWN, SYS_CHROOT]

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.17
      imagePullPolicy: Always
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, "-hcl=acl { enabled = true default_policy = \"allow\" tokens { agent = \"00000000-0000-0000-0000-000000000000\" } }"]

    - name: sidecar
      image: registry.dev.zextras.com/dev/carbonio-docs-editor-sidecar:latest
      imagePullPolicy: Always
