apiVersion: v1
kind: Pod
metadata:
  name: carbonio-composed-ui
  labels:
    app: carbonio-composed-ui
spec:
  containers:
    - name: app
      image: localhost/carbonio-composed-ui:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          ln -sf /ssl-certs/nginx.key /opt/zextras/conf/nginx.key
          ln -sf /ssl-certs/nginx.crt /opt/zextras/conf/nginx.crt
          exec ./entrypoint-proxy.sh
      env:
        # LDAP and MariaDB are outside the mesh
        - name: LDAP_URL
          value: "ldap://carbonio-openldap:1389"
        - name: LDAP_ROOT_PASSWORD
          value: "qh6hWZvc"
        - name: LDAP_ADMIN_PASSWORD
          value: "password"
        - name: MARIADB_ROOT_PASSWORD
          value: "password"
        - name: MARIADB_URL
          value: "carbonio-mariadb"
        - name: MARIADB_PORT
          value: "3306"
      ports:
        - containerPort: 443
          hostPort: 443
        - containerPort: 6071
          hostPort: 6071
      volumeMounts:
        - name: ssl
          mountPath: /ssl-certs
    - name: memcached
      image: docker.io/memcached:1.6.38-alpine
      imagePullPolicy: Always

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.17
      imagePullPolicy: Always
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, "-hcl=acl { enabled = true default_policy = \"allow\" tokens { agent = \"00000000-0000-0000-0000-000000000000\" } }"]

    - name: sidecar
      image: registry.dev.zextras.com/dev/carbonio-proxy-sidecar:devel
      imagePullPolicy: Always

  volumes:
    - name: ssl
      hostPath:
        path: ../ssl/
        type: Directory
