apiVersion: v1
kind: Pod
metadata:
  name: carbonio-mailbox
  labels:
    app: carbonio-mailbox
spec:
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-advanced:devel
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 7071
          hostPort: 7071
        - containerPort: 5005
          hostPort: 5005
      env:
        # LDAP and MariaDB are outside the mesh
        - name: LDAP_URL
          value: "ldap://carbonio-openldap:1389"
        - name: LDAP_ROOT_PASSWORD
          value: "qh6hWZvc"
        - name: LDAP_ADMIN_PASSWORD
          value: "password"
        - name: MARIADB_ROOT_PASSWORD
          value: "password"
        - name: MARIADB_URL
          value: "carbonio-mariadb"
        - name: MARIADB_PORT
          value: "3306"
        - name: CARBONIO_FULL_QUOTA_CHECK_ENABLED
          value: "true"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/zextras/opentelemetry-javaagent.jar"
        - name: OTEL_SERVICE_NAME
          value: "mailbox"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://carbonio-monitoring:4318"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
      volumeMounts:
        - name: mailbox-data
          mountPath: /opt/zextras/data/mailbox
        - name: mailbox-index
          mountPath: /opt/zextras/index
        - name: mailbox-store
          mountPath: /opt/zextras/store
        - name: zmprov-prov
          mountPath: /tmp/provisioning.txt
          readOnly: true

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.21
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, "-hcl=acl { enabled = true default_policy = \"allow\" tokens { agent = \"00000000-0000-0000-0000-000000000000\" } }"]

    - name: sidecar-mailbox
      image: registry.dev.zextras.com/dev/carbonio-mailbox-sidecar:devel
      imagePullPolicy: Always

    - name: sidecar-admin
      image: registry.dev.zextras.com/dev/carbonio-mailbox-admin-sidecar:devel
      imagePullPolicy: Always

    - name: sidecar-nslookup
      image: registry.dev.zextras.com/dev/carbonio-mailbox-nslookup-sidecar:devel
      imagePullPolicy: Always

    - name: sidecar-internal-api
      image: registry.dev.zextras.com/dev/carbonio-mailbox-internal-api-sidecar:devel
      imagePullPolicy: Always

    - name: sidecar-advanced
      image: registry.dev.zextras.com/dev/carbonio-advanced-sidecar:devel
      imagePullPolicy: Always

    - name: sidecar-address-book
      image: registry.dev.zextras.com/dev/carbonio-address-book-sidecar:devel
      imagePullPolicy: Always

    - name: sidecar-auth
      image: registry.dev.zextras.com/dev/carbonio-auth-sidecar:devel
      imagePullPolicy: Always

  volumes:
    - name: mailbox-data
      emptyDir: {}
    - name: mailbox-index
      emptyDir: {}
    - name: mailbox-store
      emptyDir: {}
    - name: zmprov-prov
      hostPath:
        path: ./zmprov.prov
        type: File
