# Service
service.host=0.0.0.0
service.port=10000
# Database
db.postgresql.host=carbonio-postgres
db.postgresql.port=5432
# Carbonio UserManagement
carbonio.user-management.host=carbonio-user-management
carbonio.user-management.port=10000
# Lambdas
firebase.auth.lambda.endpoint=https://fake/auth
firebase.send.lambda.endpoint=https://fake/sendFirebase
apns.send.lambda.endpoint=https://fake/sendApns
