{
 "title": "Logs all services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mailbox",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"mailbox\"} |= ``"
    }
   ]
  },
  {
   "title": "Storages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"storages-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Files",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"files\"} |= ``"
    }
   ]
  }
 ]
}