apiVersion: v1
kind: Pod
metadata:
  name: carbonio-postgres
  labels:
    app: carbonio-postgres
spec:
  containers:
    - name: postgres
      image: docker.io/library/postgres:16
      imagePullPolicy: Always
      env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.21
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true

    - name: files-db-sidecar
      image: registry.dev.zextras.com/dev/carbonio-files-db-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
        - name: PGPASSWORD
          value: "password"
        - name: POSTGRES_USER
          value: "carbonio-files-adm"

    - name: mailbox-db-sidecar
      image: registry.dev.zextras.com/dev/carbonio-mailbox-db-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
        - name: PGPASSWORD
          value: "password"
        - name: POSTGRES_USER
          value: "carbonio-mailbox-adm"
    - name: carbonio-docs-connector-db-sidecar
      image: registry.dev.zextras.com/dev/carbonio-docs-connector-db-sidecar:devel
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
        - name: PGPASSWORD
          value: "password"
        - name: POSTGRES_USER
          value: "carbonio-docs-connector-adm"

  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-data
    - name: init-scripts
      hostPath:
        path: ./postgres/
        type: Directory
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
