apiVersion: v1
kind: Pod
metadata:
  name: carbonio-message-broker
  labels:
    app: carbonio-message-broker
spec:
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-message-broker:devel
      imagePullPolicy: Always
      ports:
        - containerPort: 10000
        - containerPort: 10001
      env:
        - name: RABBITMQ_NODENAME
          value: "carbonio-message-broker-clustered"
        - name: CONSUL_SETUP
          value: "true"
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: message-broker-token
          mountPath: /etc/carbonio/message-broker/service-discover

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.21
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true

    - name: sidecar
      image: registry.dev.zextras.com/dev/carbonio-message-broker-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: message-broker-token
          mountPath: /shared-tokens

  volumes:
    - name: message-broker-token
      hostPath:
        path: ./tokens/message-broker/service-discover
        type: DirectoryOrCreate
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
