apiVersion: v1
kind: Pod
metadata:
  name: carbonio-storages
  labels:
    app: carbonio-storages
spec:
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-storages-service:devel
      imagePullPolicy: Always
      env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/zextras/opentelemetry-javaagent.jar"
        - name: OTEL_SERVICE_NAME
          value: "storages-service"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://carbonio-monitoring:4318"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
      volumeMounts:
        - name: storages-data
          mountPath: /storage
        - name: storages-token
          mountPath: /etc/carbonio/storages/service-discover

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.21
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true

    - name: sidecar
      imagePullPolicy: Always
      image: registry.dev.zextras.com/dev/carbonio-storages-sidecar:devel
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: storages-token
          mountPath: /shared-tokens

  volumes:
    - name: storages-token
      hostPath:
        path: ./tokens/storages/service-discover
        type: DirectoryOrCreate
    - name: storages-data
      persistentVolumeClaim:
        claimName: storages-data
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
