{{- if eq (include "carbonio.coreEnabled" .) "true" }}
apiVersion: v1
kind: Pod
metadata:
  name: carbonio-storages
  labels:
    app: carbonio-storages
spec:
{{- if eq .Values.platform "k3s" }}
  enableServiceLinks: false
  imagePullSecrets:
    - name: {{ .Values.image.pullSecret.name }}
{{- end }}
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-storages-service:devel
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: JDK_JAVA_OPTIONS
          value: "-Xms128m -Xmx512m"
        - name: QUARKUS_OTEL_SDK_DISABLED
          value: "{{ not .Values.monitoring.enabled }}"
        - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://carbonio-monitoring:4317"
      volumeMounts:
        - name: storages-data
          mountPath: /storage
        - name: storages-token
          mountPath: /etc/carbonio/storages/service-discover

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.21
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true

    - name: sidecar
      image: registry.dev.zextras.com/dev/carbonio-storages-sidecar:devel
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: storages-token
          mountPath: /shared-tokens
  volumes:
    - name: storages-token
      emptyDir: {}
    - name: storages-data
      persistentVolumeClaim:
        claimName: storages-data
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
{{- end }}
