{{- if eq (include "carbonio.coreEnabled" .) "true" }}
apiVersion: v1
kind: Pod
metadata:
  name: carbonio-catalog
  labels:
    app: carbonio-catalog
spec:
{{- if eq .Values.platform "k3s" }}
  enableServiceLinks: false
  imagePullSecrets:
    - name: {{ .Values.image.pullSecret.name }}
{{- end }}
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-catalog:devel
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumeMounts:
        - name: catalog-token
          mountPath: /etc/carbonio/catalog/service-discover

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.21
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true

    - name: sidecar
      image: registry.dev.zextras.com/dev/carbonio-catalog-sidecar:devel
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: catalog-token
          mountPath: /shared-tokens
  volumes:
    - name: catalog-token
      emptyDir: {}
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
{{- end }}
