{{- if eq (include "carbonio.coreEnabled" .) "true" }}
{{- if eq .Values.platform "k3s" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbonio-user-management
  labels:
    app: carbonio-user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbonio-user-management
  template:
    metadata:
      labels:
        app: carbonio-user-management
    spec:
{{ include "carbonio.deployment.k3sPodDefaults" . | indent 6 }}
{{ include "carbonio.user-management.podbody" . | indent 6 }}
{{- else }}
apiVersion: v1
kind: Pod
metadata:
  name: carbonio-user-management
  labels:
    app: carbonio-user-management
spec:
{{ include "carbonio.user-management.podbody" . | indent 2 }}
{{- end }}
{{- end }}
