{{- if eq (include "carbonio.coreEnabled" .) "true" }}
apiVersion: v1
kind: Pod
metadata:
  name: memcached
  labels:
    app: memcached
spec:
{{- if eq .Values.platform "k3s" }}
  enableServiceLinks: false
  imagePullSecrets:
    - name: {{ .Values.image.pullSecret.name }}
{{- end }}
  containers:
    - name: memcached
      image: docker.io/library/memcached:1.6.38-alpine
      ports:
        - containerPort: 11211
{{- end }}
