apiVersion: v1
kind: Pod
metadata:
  name: carbonio-files
  labels:
    app: carbonio-files
spec:
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-files:devel
      imagePullPolicy: Always
      env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/zextras/opentelemetry-javaagent.jar -Dsun.net.inetaddr.ttl=0"
        - name: _JAVA_OPTIONS
          value: "-Xms128m -Xmx512m"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://carbonio-monitoring:4318"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
      command: ["/bin/sh", "-c"]
      args:
        - |
          while [ ! -f /etc/carbonio/files/service-discover/token ]; do sleep 1; done
          export CONSUL_HTTP_TOKEN=$(cat /etc/carbonio/files/service-discover/token)
          exec /app/entrypoint.sh
      volumeMounts:
        - name: files-token
          mountPath: /etc/carbonio/files/service-discover

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.21
      imagePullPolicy: Always
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true

    - name: sidecar
      image: registry.dev.zextras.com/dev/carbonio-files-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: files-token
          mountPath: /shared-tokens
  volumes:
    - name: files-token
      hostPath:
        path: ./tokens/files/service-discover
        type: DirectoryOrCreate
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
