apiVersion: v1
kind: Pod
metadata:
  name: carbonio-message-broker
  labels:
    app: carbonio-message-broker
spec:
  containers:
    - name: message-broker
      image: registry.dev.zextras.com/dev/carbonio-message-broker:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: broker-data
          mountPath: /var/lib/rabbitmq
  volumes:
    - name: broker-data
      persistentVolumeClaim:
        claimName: broker-data
