apiVersion: v1
kind: Pod
metadata:
  name: carbonio-monitoring
  labels:
    app: carbonio-monitoring
spec:
  containers:
    - name: lgtm
      image: docker.io/grafana/otel-lgtm:latest
      ports:
        - containerPort: 3000
          hostPort: 3000
        - containerPort: 4317
          hostPort: 4317
        - containerPort: 4318
          hostPort: 4318
      volumeMounts:
        - name: custom-dashboards-config
          mountPath: /otel-lgtm/grafana/conf/provisioning/dashboards/custom.yaml
          readOnly: true
        - name: logs-all-services-dashboard
          mountPath: /custom-dashboards/logs-all-services-dashboard.json
          readOnly: true
        - name: traces-dashboard
          mountPath: /custom-dashboards/traces-dashboard.json
          readOnly: true

  volumes:
    - name: custom-dashboards-config
      hostPath:
        path: ./monitoring/custom-dashboards.yaml
        type: File
    - name: logs-all-services-dashboard
      hostPath:
        path: ./monitoring/logs-all-services-dashboard.json
        type: File
    - name: traces-dashboard
      hostPath:
        path: ./monitoring/traces-dashboard.json
        type: File
