apiVersion: v1
kind: Pod
metadata:
  name: carbonio-message-dispatcher
  labels:
    app: carbonio-message-dispatcher
spec:
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-message-dispatcher-ce:devel
      imagePullPolicy: Always

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.17
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, "-hcl=acl { enabled = true default_policy = \"allow\" tokens { agent = \"00000000-0000-0000-0000-000000000000\" } }"]

    - name: sidecar
      image: registry.dev.zextras.com/dev/carbonio-message-dispatcher-sidecar:latest
      imagePullPolicy: Always
