apiVersion: v1
kind: Pod
metadata:
  name: carbonio-mailbox-2
  labels:
    app: carbonio-mailbox
spec:
  hostname: carbonio-mailbox-2
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-advanced:devel
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
        - containerPort: 7071
      env:
        # LDAP and MariaDB are outside the mesh
        - name: MAILBOXD_JAVA_OPTS
          value: "-Xss256k -Xms128m -Xmx1024m"
        - name: LDAP_URL
          value: "ldap://carbonio-openldap:1389"
        - name: LDAP_ROOT_PASSWORD
          value: "qh6hWZvc"
        - name: LDAP_ADMIN_PASSWORD
          value: "password"
        - name: MARIADB_ROOT_PASSWORD
          value: "password"
        - name: MARIADB_URL
          value: "localhost"
        - name: MARIADB_PORT
          value: "3306"
        - name: CARBONIO_FULL_QUOTA_CHECK_ENABLED
          value: "true"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/zextras/opentelemetry-javaagent.jar"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://carbonio-monitoring:4318"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
      volumeMounts:
        - name: mailbox-2-data
          mountPath: /opt/zextras/data/mailbox
        - name: mailbox-2-index
          mountPath: /opt/zextras/index
        - name: mailbox-2-store
          mountPath: /opt/zextras/store
        - name: token-mailbox
          mountPath: /etc/carbonio/mailbox/service-discover
        - name: token-mailbox-admin
          mountPath: /etc/carbonio/mailbox-admin/service-discover
        - name: token-mailbox-nslookup
          mountPath: /etc/carbonio/mailbox-nslookup/service-discover
        - name: token-mailbox-internal-api
          mountPath: /etc/carbonio/mailbox-internal-api/service-discover
        - name: token-advanced
          mountPath: /etc/carbonio/advanced/service-discover
        - name: token-address-book
          mountPath: /etc/carbonio/address-book/service-discover
        - name: token-auth
          mountPath: /etc/carbonio/auth/service-discover

    - name: mariadb
      image: registry.dev.zextras.com/dev/carbonio-mariadb:devel
      imagePullPolicy: Always
      volumeMounts:
        - name: mailbox-2-mariadb-data
          mountPath: /var/lib/mysql

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.21
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true

    - name: sidecar-mailbox
      image: registry.dev.zextras.com/dev/carbonio-mailbox-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: token-mailbox
          mountPath: /shared-tokens

    - name: sidecar-admin
      image: registry.dev.zextras.com/dev/carbonio-mailbox-admin-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: token-mailbox-admin
          mountPath: /shared-tokens

    - name: sidecar-nslookup
      image: registry.dev.zextras.com/dev/carbonio-mailbox-nslookup-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: token-mailbox-nslookup
          mountPath: /shared-tokens

    - name: sidecar-internal-api
      image: registry.dev.zextras.com/dev/carbonio-mailbox-internal-api-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: token-mailbox-internal-api
          mountPath: /shared-tokens

    - name: sidecar-advanced
      image: registry.dev.zextras.com/dev/carbonio-advanced-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: token-advanced
          mountPath: /shared-tokens

    - name: sidecar-address-book
      image: registry.dev.zextras.com/dev/carbonio-address-book-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: token-address-book
          mountPath: /shared-tokens

    - name: sidecar-auth
      image: registry.dev.zextras.com/dev/carbonio-auth-sidecar:devel
      imagePullPolicy: Always
      env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: consul-acl
              key: bootstrap-token
      volumeMounts:
        - name: token-auth
          mountPath: /shared-tokens

  volumes:
    - name: token-mailbox
      hostPath:
        path: ./tokens/mailbox/service-discover
        type: DirectoryOrCreate
    - name: token-mailbox-admin
      hostPath:
        path: ./tokens/mailbox-admin/service-discover
        type: DirectoryOrCreate
    - name: token-mailbox-nslookup
      hostPath:
        path: ./tokens/mailbox-nslookup/service-discover
        type: DirectoryOrCreate
    - name: token-mailbox-internal-api
      hostPath:
        path: ./tokens/mailbox-internal-api/service-discover
        type: DirectoryOrCreate
    - name: token-advanced
      hostPath:
        path: ./tokens/advanced/service-discover
        type: DirectoryOrCreate
    - name: token-address-book
      hostPath:
        path: ./tokens/address-book/service-discover
        type: DirectoryOrCreate
    - name: token-auth
      hostPath:
        path: ./tokens/auth/service-discover
        type: DirectoryOrCreate
    - name: mailbox-2-data
      persistentVolumeClaim:
        claimName: mailbox-2-data
    - name: mailbox-2-index
      persistentVolumeClaim:
        claimName: mailbox-2-index
    - name: mailbox-2-store
      persistentVolumeClaim:
        claimName: mailbox-2-store
    - name: mailbox-2-mariadb-data
      persistentVolumeClaim:
        claimName: mailbox-2-mariadb-data
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
