{{- if .Values.image.pullSecret.create }}
{{- $ps := .Values.image.pullSecret }}
{{- $auth := printf "%s:%s" $ps.username $ps.password | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $ps.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` $ps.server $ps.username $ps.password $auth | b64enc }}
{{- end }}
