{{- if .Values.groups.todo.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: carbonio-videoserver
  labels:
    app: carbonio-videoserver
spec:
{{- if eq .Values.platform "k3s" }}
  enableServiceLinks: false
  imagePullSecrets:
    - name: {{ .Values.image.pullSecret.name }}
{{- end }}
  containers:
    - name: app
      image: {{ required "images.carbonio-videoserver-ce is required" (index .Values.images "carbonio-videoserver-ce") }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - containerPort: 8088
        - containerPort: 20000
          hostPort: 20000
          protocol: UDP
        - containerPort: 20200
          hostPort: 20200
          protocol: UDP
      volumeMounts:
        - name: videoserver-data
          mountPath: /var/lib/videoserver

    - name: consul-agent
      image: {{ required "images.consul is required" (index .Values.images "consul") }}
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true
{{- if eq .Values.platform "podman" }}
        - name: videoserver-consul-data
          mountPath: /consul/data
{{- end }}

    - name: sidecar
      image: {{ required "images.carbonio-videoserver-sidecar is required" (index .Values.images "carbonio-videoserver-sidecar") }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
  volumes:
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
    - name: videoserver-data
      persistentVolumeClaim:
        claimName: videoserver-data
{{- if eq .Values.platform "podman" }}
    - name: videoserver-consul-data
      persistentVolumeClaim:
        claimName: videoserver-consul-data
{{- end }}
{{- end }}
