apiVersion: v1
kind: Pod
metadata:
  name: carbonio-message-dispatcher
  labels:
    app: carbonio-message-dispatcher
spec:
  containers:
    - name: app
      image: registry.dev.zextras.com/dev/carbonio-message-dispatcher-ce:devel
      imagePullPolicy: Always

    - name: consul-agent
      image: docker.io/hashicorp/consul:1.21
      args: [agent, -client=0.0.0.0, -bind=0.0.0.0, -retry-join=consul-server, -grpc-port=8502, -config-dir=/consul/acl]
      volumeMounts:
        - name: consul-agent-acl
          mountPath: /consul/acl/consul-agent-acl.hcl
          subPath: consul-agent-acl.hcl
          readOnly: true

    - name: sidecar
      image: registry.dev.zextras.com/dev/carbonio-message-dispatcher-sidecar:latest
      imagePullPolicy: Always

  volumes:
    - name: consul-agent-acl
      configMap:
        name: consul-acl
        items:
          - key: consul-agent-acl.hcl
            path: consul-agent-acl.hcl
